import type { WorkoutDaySummary } from '@/lib/types';

export const SEED_TEMPLATE_ID = 'seed_push_pull_legs_arms_v1';

export const SEED_TEMPLATE_SOURCE = 'uploaded_workout_schedule_pdf';

export const SEED_WEEKLY_SPLIT: WorkoutDaySummary[] = [
  {
    id: 'seed_day_monday_chest_triceps',
    dayOfWeek: 1,
    displayOrder: 1,
    name: 'Monday',
    muscleGroup: 'Chest + Triceps',
    isRestDay: false,
    isOptional: false,
    exercises: [
      'Flat Bench Press',
      'Incline Dumbbell Press',
      'Cable Fly or Pec Deck',
      'Tricep Pushdown',
      'Overhead DB Extension',
      'Dips',
    ],
  },
  {
    id: 'seed_day_tuesday_back_biceps',
    dayOfWeek: 2,
    displayOrder: 2,
    name: 'Tuesday',
    muscleGroup: 'Back + Biceps',
    isRestDay: false,
    isOptional: false,
    exercises: [
      'Pull-Ups or Lat Pulldown',
      'Barbell Row',
      'Seated Cable Row',
      'Dumbbell Pullover',
      'Barbell Curl',
      'Incline Dumbbell Curl',
    ],
  },
  {
    id: 'seed_day_wednesday_shoulders_abs',
    dayOfWeek: 3,
    displayOrder: 3,
    name: 'Wednesday',
    muscleGroup: 'Shoulders + Abs',
    isRestDay: false,
    isOptional: false,
    exercises: [
      'Seated Shoulder Press',
      'DB Lateral Raise',
      'Reverse Pec Deck',
      'Upright Row',
      'Hanging Leg Raise',
      'Cable Crunch',
    ],
  },
  {
    id: 'seed_day_thursday_quads_hamstrings',
    dayOfWeek: 4,
    displayOrder: 4,
    name: 'Thursday',
    muscleGroup: 'Quads + Hamstrings',
    isRestDay: false,
    isOptional: false,
    exercises: [
      'Barbell Squat or Leg Press',
      'Walking Lunges',
      'Leg Extension',
      'Lying Leg Curl',
      'Romanian Deadlift',
      'Standing Calf Raise',
    ],
  },
  {
    id: 'seed_day_friday_arms',
    dayOfWeek: 5,
    displayOrder: 5,
    name: 'Friday',
    muscleGroup: 'Biceps + Triceps',
    isRestDay: false,
    isOptional: false,
    exercises: [
      'Close-Grip Bench Press',
      'Tricep Pushdown',
      'Skull Crushers',
      'Barbell Curl',
      'Hammer Curl',
      'Preacher Curl',
    ],
  },
  {
    id: 'seed_day_saturday_optional',
    dayOfWeek: 6,
    displayOrder: 6,
    name: 'Saturday',
    muscleGroup: 'Rest / Cardio + Core optional',
    isRestDay: true,
    isOptional: true,
    exercises: ['Cardio + Core Optional'],
  },
  {
    id: 'seed_day_sunday_rest',
    dayOfWeek: 7,
    displayOrder: 7,
    name: 'Sunday',
    muscleGroup: 'Rest',
    isRestDay: true,
    isOptional: false,
    exercises: [],
  },
];
